***4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.***

**1) Initialize an empty array with size 2X2.**

In [ ]:
import numpy as np

array = np.empty((2, 2))
print(array)


[[3.13940507e-315 0.00000000e+000]
 [3.31971640e-316 3.06852525e-315]]


**2) Initialize an all one array with size 4X2.**

In [ ]:
allone_arr = np.ones((4,2))
print ("All one array  \n", allone_arr, " with dimension", allone_arr.shape,"\n")

All one array  
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]  with dimension (4, 2) 



**3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}**

In [ ]:
array = np.full((3, 3), 7)
print(array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


**4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}**

In [ ]:
#  4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
arrays = np.array([[1, 2, 3], [4, 5, 6]])

zero_arr = np.zeros_like(arrays)
print(zero_arr)

[[0 0 0]
 [0 0 0]]


**5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}**

In [ ]:
arrays = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

ones_arr = np.ones_like(arrays)
print(ones_arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


**6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}**

In [ ]:
# Existing List
new_list = [1, 2, 3, 4]

# Convert to NumPy array
numpy_array = np.array(new_list)
print(numpy_array)

[1 2 3 4]


***Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:***

**1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.**

In [ ]:
array = np.arange(10, 50)
print(array)

[]


**2. Create a 3X3 matrix with values ranging from 0 to 8.**
{**Hint:look for np.reshape**()}

In [ ]:
array = np.arange(0, 9)
array_reshaped = np.reshape(array, (3, 3))
print(array_reshaped)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


**3. Create a 3X3 identity matrix.**{**Hint:np.eye**()}

In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**4. Create a random array of size 30 and find the mean of the array.**
{**Hint:check for np.random.random() and array.mean() function**}

In [ ]:
array = np.random.random(30)
array_mean = array.mean()
print(array_mean)

0.5431417723607452


**5. Create a 10X10 array with random values and find the minimum and maximum values.**

In [ ]:
import numpy as np

arr = np.random.random((10, 10))
min_val = arr.min()
max_val = arr.max()

print("Array:\n", arr)
print("Minimum value:", min_val)
print("Maximum value:", max_val)

Array:
 [[0.67646141 0.15014178 0.1369091  0.41659061 0.46253847 0.12011309
  0.84792096 0.88704373 0.66642438 0.14750333]
 [0.95237581 0.06632296 0.56210958 0.90648307 0.53114414 0.5946243
  0.31376782 0.74016344 0.09698008 0.32918025]
 [0.43938428 0.26935894 0.05326181 0.79165151 0.38674229 0.48488928
  0.11452059 0.49454167 0.94677054 0.31548713]
 [0.220371   0.83490675 0.02939088 0.7098678  0.69285134 0.79088596
  0.91570189 0.41343461 0.89554786 0.88958354]
 [0.49583693 0.09179162 0.87287118 0.34390867 0.35626809 0.81606042
  0.59230782 0.4776721  0.83475698 0.45990824]
 [0.55013011 0.64930903 0.78729997 0.13878947 0.28656566 0.37548247
  0.52288216 0.52152833 0.54749025 0.46554657]
 [0.08346392 0.86765076 0.38889137 0.84139261 0.51439646 0.01551996
  0.84804842 0.41845422 0.87906035 0.20418162]
 [0.71002704 0.65922726 0.34573313 0.89006373 0.14853637 0.72992752
  0.847398   0.97981082 0.79696333 0.36630365]
 [0.75912066 0.8098988  0.16124686 0.91825293 0.7518404  0.63912999
  0.5

**6. Create a zero array of size 10 and replace 5th element with 1.**

In [ ]:
arr = np.zeros(10)
arr[4] = 1   # 5th element (index 4)

print(arr)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**7. Reverse an array arr = [1,2,0,0,4,0].**

In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]

print(reversed_arr)


[0 4 0 0 2 1]


**8. Create a 2d array with 1 on border and 0 inside.**

In [ ]:
arr = np.ones((6, 6))
arr[1:-1, 1:-1] = 0

print(arr)


[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


**9. Create a 8X8 matrix and fill it with a checkerboard pattern.**

In [ ]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


***Problem - 3: Array Operations:***


**For the following arrays:**
**x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:**

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

**1. Add the two array.**

In [ ]:
add_xy = x + y
print(add_xy)

[[ 6  8]
 [10 13]]


**2. Subtract the two array.**

In [ ]:
sub_xy = x - y
print(sub_xy)


[[-4 -4]
 [-4 -3]]


**3. Multiply the array with any integers of your choice.**

In [ ]:
mul_x = x * 3
print(mul_x)


[[ 3  6]
 [ 9 15]]


**4. Find the square of each element of the array.**

In [ ]:
square_x = x ** 2
print(square_x)


[[ 1  4]
 [ 9 25]]


**5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.**

In [ ]:
dot_vw = np.dot(v, w)
print(dot_vw)


219


In [ ]:
dot_xv = np.dot(x, v)
print(dot_xv)


In [ ]:
dot_xy = np.dot(x, y)
print(dot_xy)


6**. Concatenate x(and)y along row and Concatenate v(and)w along column. **bold text**
**Hint:try np.concatenate**()** or np.vstack**() **functions**.

In [ ]:
concat_row = np.vstack((x, y))
print(concat_row)


In [ ]:
concat_col = np.column_stack((v, w))
print(concat_col)


**7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error**?

In [ ]:
print("Because: x is 2D → shape (2,2)\n\nv is 1D → shape (2,)\n\nNumpy cannot concatenate arrays of different dimensions")
np.concatenate((x, v.reshape(1, -1)), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

***Problem - 4: Matrix Operations:***

**• For the following arrays:**
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

**Prove following with Numpy:**
**1. Prove** A.A−1 = I.

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print(identity)



[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


**2. Prove **AB ̸= BA.

In [ ]:

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)


AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


**3. Prove** (AB) T = BTAT.

In [ ]:
lhs = (AB).T
rhs = np.dot(B.T, A.T)

print(lhs)
print(rhs)


[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


**• Solve the following system of Linear equation using Inverse Methods.**

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
**• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function**
of Numpy}

In [ ]:


A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3,  1, -1]
])

B = np.array([-1, -3, 9])



SyntaxError: invalid decimal literal (ipython-input-4036702098.py, line 1)

In [ ]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution (x, y, z):", X)


Solution (x, y, z): [[-8.   -5.  ]
 [ 7.25  4.5 ]]


In [ ]:
X2 = np.linalg.solve(A, B)
print(X2)


[[-8.   -5.  ]
 [ 7.25  4.5 ]]
